version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - elk

  logstash:
    image: logstash:7.12.1
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk

  kibana:
    image: kibana:7.12.1
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk

networks:
  elk:
